[package]
name = "hwl_std"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[build-dependencies]
hwl_util.workspace = true

itertools.workspace = true

[lints]
workspace = true
