[project]
name = "hwl"
version = "0.1.0"

# Limit max version for now until PyO3 supports newer versions.
requires-python = ">=3.12,<=3.13"

[build-system]
requires = ["maturin>=1.11"]
build-backend = "maturin"

[tool.maturin]
features = ["pyo3/extension-module"]
